version: "3.7"

services:
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  back:
    build:
      context: ./library_back
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
  front:
    build:
      context: ./library_front
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - front
