version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: library_db
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
  back:
    build:
      context: ./library_back
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
  front:
    build:
      context: ./library_front
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back
